services:
  discovery-server:
    build:
      context: ./backend/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
    networks:
      microservices:
        aliases:
          - discovery-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  gateway-service:
    build:
      context: ./backend/gateway-service
    container_name: gateway-service
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8890:8890"
    environment:
      - EUREKA_SERVER_URI=http://discovery-server:8761/eureka
    networks:
      - microservices

  vehicles-service:
    build:
      context: ./backend/vehicles-service
    container_name: vehicles-service
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8085:8085"
    environment:
      - EUREKA_SERVER_URI=http://discovery-server:8761/eureka
    networks:
      - microservices

  monitor-prosumer:
    build:
      context: ./backend/monitors-prosumer
    container_name: monitor-prosumer
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      - EUREKA_SERVER_URI=http://discovery-server:8761/eureka
    networks:
      - microservices

  datagenerator-service:
    build:
      context: ./backend/datagenerator-service
    container_name: datagenerator-service
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER_URI=http://discovery-server:8761/eureka
    networks:
      - microservices

  amend-prosumer:
    build:
      context: ./backend/amend-prosumer
    container_name: amend-prosumer
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8084:8084"
    environment:
      - EUREKA_SERVER_URI=http://discovery-server:8761/eureka
    networks:
      - microservices

  frontend:
    image: nginx:stable-alpine
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - gateway-service
    build:
      context: ./frontend
    ports:
      - "3001:80"
      - "3443:443"
    environment:
      NGINX_HOST: ${FRONTEND_HOST:-localhost}
      API_URL: http://gateway-service:8890      
    command: /bin/ash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/ngnix.asr.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
