// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitor-service.proto

package univaq.disim.sose.monitorservice.web.grpc.stubs;

public final class MonitorServiceOuterClass {
  private MonitorServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SpeedViolationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SpeedViolation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string monitorId = 1;</code>
     * @return The monitorId.
     */
    java.lang.String getMonitorId();
    /**
     * <code>string monitorId = 1;</code>
     * @return The bytes for monitorId.
     */
    com.google.protobuf.ByteString
        getMonitorIdBytes();

    /**
     * <code>string vehicleRegistrationNumber = 2;</code>
     * @return The vehicleRegistrationNumber.
     */
    java.lang.String getVehicleRegistrationNumber();
    /**
     * <code>string vehicleRegistrationNumber = 2;</code>
     * @return The bytes for vehicleRegistrationNumber.
     */
    com.google.protobuf.ByteString
        getVehicleRegistrationNumberBytes();

    /**
     * <code>int32 vehicleSpeed = 3;</code>
     * @return The vehicleSpeed.
     */
    int getVehicleSpeed();
  }
  /**
   * Protobuf type {@code SpeedViolation}
   */
  public  static final class SpeedViolation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SpeedViolation)
      SpeedViolationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SpeedViolation.newBuilder() to construct.
    private SpeedViolation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SpeedViolation() {
      monitorId_ = "";
      vehicleRegistrationNumber_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SpeedViolation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SpeedViolation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              monitorId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              vehicleRegistrationNumber_ = s;
              break;
            }
            case 24: {

              vehicleSpeed_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.internal_static_SpeedViolation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.internal_static_SpeedViolation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation.class, univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation.Builder.class);
    }

    public static final int MONITORID_FIELD_NUMBER = 1;
    private volatile java.lang.Object monitorId_;
    /**
     * <code>string monitorId = 1;</code>
     * @return The monitorId.
     */
    public java.lang.String getMonitorId() {
      java.lang.Object ref = monitorId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        monitorId_ = s;
        return s;
      }
    }
    /**
     * <code>string monitorId = 1;</code>
     * @return The bytes for monitorId.
     */
    public com.google.protobuf.ByteString
        getMonitorIdBytes() {
      java.lang.Object ref = monitorId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        monitorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VEHICLEREGISTRATIONNUMBER_FIELD_NUMBER = 2;
    private volatile java.lang.Object vehicleRegistrationNumber_;
    /**
     * <code>string vehicleRegistrationNumber = 2;</code>
     * @return The vehicleRegistrationNumber.
     */
    public java.lang.String getVehicleRegistrationNumber() {
      java.lang.Object ref = vehicleRegistrationNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehicleRegistrationNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string vehicleRegistrationNumber = 2;</code>
     * @return The bytes for vehicleRegistrationNumber.
     */
    public com.google.protobuf.ByteString
        getVehicleRegistrationNumberBytes() {
      java.lang.Object ref = vehicleRegistrationNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehicleRegistrationNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VEHICLESPEED_FIELD_NUMBER = 3;
    private int vehicleSpeed_;
    /**
     * <code>int32 vehicleSpeed = 3;</code>
     * @return The vehicleSpeed.
     */
    public int getVehicleSpeed() {
      return vehicleSpeed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMonitorIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, monitorId_);
      }
      if (!getVehicleRegistrationNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, vehicleRegistrationNumber_);
      }
      if (vehicleSpeed_ != 0) {
        output.writeInt32(3, vehicleSpeed_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMonitorIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, monitorId_);
      }
      if (!getVehicleRegistrationNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, vehicleRegistrationNumber_);
      }
      if (vehicleSpeed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, vehicleSpeed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation)) {
        return super.equals(obj);
      }
      univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation other = (univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation) obj;

      if (!getMonitorId()
          .equals(other.getMonitorId())) return false;
      if (!getVehicleRegistrationNumber()
          .equals(other.getVehicleRegistrationNumber())) return false;
      if (getVehicleSpeed()
          != other.getVehicleSpeed()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MONITORID_FIELD_NUMBER;
      hash = (53 * hash) + getMonitorId().hashCode();
      hash = (37 * hash) + VEHICLEREGISTRATIONNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getVehicleRegistrationNumber().hashCode();
      hash = (37 * hash) + VEHICLESPEED_FIELD_NUMBER;
      hash = (53 * hash) + getVehicleSpeed();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SpeedViolation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SpeedViolation)
        univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.internal_static_SpeedViolation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.internal_static_SpeedViolation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation.class, univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation.Builder.class);
      }

      // Construct using univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        monitorId_ = "";

        vehicleRegistrationNumber_ = "";

        vehicleSpeed_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.internal_static_SpeedViolation_descriptor;
      }

      @java.lang.Override
      public univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation getDefaultInstanceForType() {
        return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation.getDefaultInstance();
      }

      @java.lang.Override
      public univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation build() {
        univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation buildPartial() {
        univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation result = new univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation(this);
        result.monitorId_ = monitorId_;
        result.vehicleRegistrationNumber_ = vehicleRegistrationNumber_;
        result.vehicleSpeed_ = vehicleSpeed_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation) {
          return mergeFrom((univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation other) {
        if (other == univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation.getDefaultInstance()) return this;
        if (!other.getMonitorId().isEmpty()) {
          monitorId_ = other.monitorId_;
          onChanged();
        }
        if (!other.getVehicleRegistrationNumber().isEmpty()) {
          vehicleRegistrationNumber_ = other.vehicleRegistrationNumber_;
          onChanged();
        }
        if (other.getVehicleSpeed() != 0) {
          setVehicleSpeed(other.getVehicleSpeed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object monitorId_ = "";
      /**
       * <code>string monitorId = 1;</code>
       * @return The monitorId.
       */
      public java.lang.String getMonitorId() {
        java.lang.Object ref = monitorId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          monitorId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string monitorId = 1;</code>
       * @return The bytes for monitorId.
       */
      public com.google.protobuf.ByteString
          getMonitorIdBytes() {
        java.lang.Object ref = monitorId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          monitorId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string monitorId = 1;</code>
       * @param value The monitorId to set.
       * @return This builder for chaining.
       */
      public Builder setMonitorId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        monitorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string monitorId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonitorId() {
        
        monitorId_ = getDefaultInstance().getMonitorId();
        onChanged();
        return this;
      }
      /**
       * <code>string monitorId = 1;</code>
       * @param value The bytes for monitorId to set.
       * @return This builder for chaining.
       */
      public Builder setMonitorIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        monitorId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object vehicleRegistrationNumber_ = "";
      /**
       * <code>string vehicleRegistrationNumber = 2;</code>
       * @return The vehicleRegistrationNumber.
       */
      public java.lang.String getVehicleRegistrationNumber() {
        java.lang.Object ref = vehicleRegistrationNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vehicleRegistrationNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string vehicleRegistrationNumber = 2;</code>
       * @return The bytes for vehicleRegistrationNumber.
       */
      public com.google.protobuf.ByteString
          getVehicleRegistrationNumberBytes() {
        java.lang.Object ref = vehicleRegistrationNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vehicleRegistrationNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vehicleRegistrationNumber = 2;</code>
       * @param value The vehicleRegistrationNumber to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleRegistrationNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vehicleRegistrationNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string vehicleRegistrationNumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleRegistrationNumber() {
        
        vehicleRegistrationNumber_ = getDefaultInstance().getVehicleRegistrationNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string vehicleRegistrationNumber = 2;</code>
       * @param value The bytes for vehicleRegistrationNumber to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleRegistrationNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vehicleRegistrationNumber_ = value;
        onChanged();
        return this;
      }

      private int vehicleSpeed_ ;
      /**
       * <code>int32 vehicleSpeed = 3;</code>
       * @return The vehicleSpeed.
       */
      public int getVehicleSpeed() {
        return vehicleSpeed_;
      }
      /**
       * <code>int32 vehicleSpeed = 3;</code>
       * @param value The vehicleSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleSpeed(int value) {
        
        vehicleSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 vehicleSpeed = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleSpeed() {
        
        vehicleSpeed_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SpeedViolation)
    }

    // @@protoc_insertion_point(class_scope:SpeedViolation)
    private static final univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation();
    }

    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SpeedViolation>
        PARSER = new com.google.protobuf.AbstractParser<SpeedViolation>() {
      @java.lang.Override
      public SpeedViolation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpeedViolation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SpeedViolation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SpeedViolation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.SpeedViolation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GenerateSpeedViolationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GenerateSpeedViolationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 numberOfViolations = 1;</code>
     * @return The numberOfViolations.
     */
    int getNumberOfViolations();
  }
  /**
   * Protobuf type {@code GenerateSpeedViolationRequest}
   */
  public  static final class GenerateSpeedViolationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GenerateSpeedViolationRequest)
      GenerateSpeedViolationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenerateSpeedViolationRequest.newBuilder() to construct.
    private GenerateSpeedViolationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenerateSpeedViolationRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GenerateSpeedViolationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GenerateSpeedViolationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              numberOfViolations_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.internal_static_GenerateSpeedViolationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.internal_static_GenerateSpeedViolationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest.class, univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest.Builder.class);
    }

    public static final int NUMBEROFVIOLATIONS_FIELD_NUMBER = 1;
    private int numberOfViolations_;
    /**
     * <code>int32 numberOfViolations = 1;</code>
     * @return The numberOfViolations.
     */
    public int getNumberOfViolations() {
      return numberOfViolations_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numberOfViolations_ != 0) {
        output.writeInt32(1, numberOfViolations_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numberOfViolations_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, numberOfViolations_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest)) {
        return super.equals(obj);
      }
      univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest other = (univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest) obj;

      if (getNumberOfViolations()
          != other.getNumberOfViolations()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBEROFVIOLATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfViolations();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GenerateSpeedViolationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GenerateSpeedViolationRequest)
        univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.internal_static_GenerateSpeedViolationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.internal_static_GenerateSpeedViolationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest.class, univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest.Builder.class);
      }

      // Construct using univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numberOfViolations_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.internal_static_GenerateSpeedViolationRequest_descriptor;
      }

      @java.lang.Override
      public univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest getDefaultInstanceForType() {
        return univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest build() {
        univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest buildPartial() {
        univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest result = new univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest(this);
        result.numberOfViolations_ = numberOfViolations_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest) {
          return mergeFrom((univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest other) {
        if (other == univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest.getDefaultInstance()) return this;
        if (other.getNumberOfViolations() != 0) {
          setNumberOfViolations(other.getNumberOfViolations());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int numberOfViolations_ ;
      /**
       * <code>int32 numberOfViolations = 1;</code>
       * @return The numberOfViolations.
       */
      public int getNumberOfViolations() {
        return numberOfViolations_;
      }
      /**
       * <code>int32 numberOfViolations = 1;</code>
       * @param value The numberOfViolations to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfViolations(int value) {
        
        numberOfViolations_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numberOfViolations = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberOfViolations() {
        
        numberOfViolations_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GenerateSpeedViolationRequest)
    }

    // @@protoc_insertion_point(class_scope:GenerateSpeedViolationRequest)
    private static final univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest();
    }

    public static univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenerateSpeedViolationRequest>
        PARSER = new com.google.protobuf.AbstractParser<GenerateSpeedViolationRequest>() {
      @java.lang.Override
      public GenerateSpeedViolationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GenerateSpeedViolationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenerateSpeedViolationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenerateSpeedViolationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public univaq.disim.sose.monitorservice.web.grpc.stubs.MonitorServiceOuterClass.GenerateSpeedViolationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpeedViolation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpeedViolation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateSpeedViolationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateSpeedViolationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025monitor-service.proto\032\033google/protobuf" +
      "/empty.proto\"\\\n\016SpeedViolation\022\021\n\tmonito" +
      "rId\030\001 \001(\t\022!\n\031vehicleRegistrationNumber\030\002" +
      " \001(\t\022\024\n\014vehicleSpeed\030\003 \001(\005\";\n\035GenerateSp" +
      "eedViolationRequest\022\032\n\022numberOfViolation" +
      "s\030\001 \001(\0052^\n\016MonitorService\022L\n\027GenerateSpe" +
      "edViolations\022\036.GenerateSpeedViolationReq" +
      "uest\032\017.SpeedViolation0\001B1\n/univaq.disim." +
      "sose.monitorservice.web.grpc.stubsb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_SpeedViolation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SpeedViolation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpeedViolation_descriptor,
        new java.lang.String[] { "MonitorId", "VehicleRegistrationNumber", "VehicleSpeed", });
    internal_static_GenerateSpeedViolationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GenerateSpeedViolationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateSpeedViolationRequest_descriptor,
        new java.lang.String[] { "NumberOfViolations", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
