#set ( $d = "$")
management.security.enabled: false

cxf:
  path: /
  servlet.init:
    service-list-path: info
  jaxrs:
    component-scan: true
    classes-scan-packages: org.apache.cxf.jaxrs.swagger,org.apache.cxf.metrics

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${d}{EUREKA_SERVER_URI:eureka-registry}:${d}{EUREKA_SERVER_PORT:8080}${d}{EUREKA_BASE_PATH:/sose}/eureka/
  instance:
    prefer-ip-address: true
    statusPageUrlPath: ${d}{cxf.path}/${d}{cxf.servlet.init.service-list-path}
    # not work because / is managed by CXF (moving CXF path to: /api solve, but service must be on the root for eureka+zuul+feign logic)
    healthCheckUrlPath: /actuator/health
    instanceId: ${d}{spring.application.name}:${d}{spring.application.instance_id:${d}{random.value}}
    metadataMap:
      # all under metadataMap is ignored and passed to client
      servletPath: ${d}{cxf.path}

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:mariadb://${artifactId}-db:3306/sosedb'
    username: sose
    password: sose
    driver-class-name: 'org.mariadb.jdbc.Driver'
    hikari:
      minIdle: 10
      idle-timeout: 10000
      maximumPoolSize: 30

management.endpoints.web.exposure.include: health, info, metrics
